### ISSUE TITLE
How to send multiple files?

### ISSUE THREAD

**Issue by Macleykun** [appleboy/discord-action#6]
I'm trying to send multiple files, but isn't `*` supported?
![image](https://user-images.githubusercontent.com/26381427/142775884-24ddeb89-3fcf-45af-8c72-dd3100b295aa.png)

Did get that commt in, but it only seems to work per file sadly

**Comment by KenwoodFox** [comment]
Never fixed this?

**Comment by Macleykun** [comment]
Made a script to add each full path to it

**Comment by KenwoodFox** [comment]
Would love to see it!

**Comment by Macleykun** [comment]
Suggest making a new issue with this request
